### ISSUE TITLE
how to disable animation for item update?

### ISSUE THREAD

**Issue by ohdonpiano** [canopas/animated_reorderable_list#60]
When I edit an item in the list, e.g. rename, I save the item in a detail page, pop back, and the AnimatedReorderableListView performs both a delete and an insert animation because the page state gets updated

I'd like to disable if possible those animations and let only the widget of the item update itself, e.g. updating the Text because the model has been renamed.

Is this something achievable with the current version?

**Comment by cp-sneha-s** [comment]
Hi @ohdonpiano 

This happens because updating an item creates a different instance, causing the list to show animations. To resolve this, you should implement an equality checker by overriding the `hashCode` and `== `operator to compare only the ID of the object.

For more detailed information, please update to package version 1.0.7. We've included an updated example app that demonstrates this fix.
